### ISSUE TITLE
Lost changes

### ISSUE THREAD

**Issue by Vovaman** [VolkovLabs/business-forms#487]
1) Open my panel for edit and see my code:
![01](https://github.com/user-attachments/assets/49645cc5-87f1-4ab5-b73a-8e6c63abc227)
2) Make some changes...:
![02](https://github.com/user-attachments/assets/d0820046-a688-43bf-9d32-cb96336e1c49)
...and press ``Apply`` button.
3) After that open panel for edit again and see my previous code:
![03](https://github.com/user-attachments/assets/52d45100-eb4e-442c-9e4e-9a704e18f1b5)

**Comment by mikhail-vl** [comment]
@Vovaman Thank you for reporting the issue. We will look into it.

 What version do you use?

**Comment by Vovaman** [comment]
4.4.0

**Comment by vitPinchuk** [comment]
@Vovaman thank you for your question.

This is due to the delay in applying the changes. 

Please, note that there is a slight delay in your changes. 

Pay attention to the `save changes` button that appears (blue button under elements) 

![image](https://github.com/user-attachments/assets/3cae9ce4-c871-494e-a633-5d264e84a8a1)

As soon as you make changes and take the focus off of the input, the  `save changes` button appears. Soon it disappears. This means that the changes have been applied and you can press the `Apply` button 

Correct save changes
https://www.loom.com/share/3023a3ba7b08427e9d1d31737920265a?sid=3feec258-1f25-4921-affd-cff4bdb51d6b

Described behavior (incorrect) 
https://www.loom.com/share/be8289aeacd34f17bd023ed7e3b1a36d
